In [36]:
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [6]:
reg = linear_model.LinearRegression()
reg.fit([[0,0], [1,1], [2,2]], [0, 1, 2])

LinearRegression()

In [7]:
reg.__dict__

{'fit_intercept': True,
 'normalize': False,
 'copy_X': True,
 'n_jobs': None,
 'n_features_in_': 2,
 'coef_': array([0.5, 0.5]),
 '_residues': array([], dtype=float64),
 'rank_': 1,
 'singular_': array([2.00000000e+00, 3.35470445e-17]),
 'intercept_': 2.220446049250313e-16}

In [117]:
reg.predict([[-4,4]])

array([0.])

In [59]:
poly = PolynomialFeatures(2)

In [86]:
X = np.array([[0,0,0], [1,1,1], [2,2,2]])
y = np.array([0, 1, 2])
X, y

(array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]),
 array([0, 1, 2]))

In [73]:
poly.fit(X)

PolynomialFeatures()

In [80]:
poly.n_output_features_

10

In [81]:
poly.powers_

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [2, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 2, 0],
       [0, 1, 1],
       [0, 0, 2]])

In [89]:
poly.get_params()

{'degree': 2, 'include_bias': True, 'interaction_only': False, 'order': 'C'}

In [88]:
poly.fit(X, y)

PolynomialFeatures()

In [49]:
poly.powers_

array([[0, 0],
       [1, 0],
       [0, 1],
       [2, 0],
       [1, 1],
       [0, 2]])

In [58]:
type(PolynomialFeatures.__bases__[1])

type

In [97]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [98]:
scaler.fit(X)

StandardScaler()

In [102]:
from sklearn.pipeline import Pipeline, make_pipeline

In [103]:
Pipeline.__bases__

(sklearn.utils.metaestimators._BaseComposition,)

In [104]:
pipe = make_pipeline(poly)

In [111]:
pipe = make_pipeline(pipe)

In [112]:
pipe

Pipeline(steps=[('pipeline',
                 Pipeline(steps=[('polynomialfeatures',
                                  PolynomialFeatures())]))])

In [113]:
import inspect
inspect.getmembers(pipe)

[('__abstractmethods__', frozenset()),
 ('__annotations__', {'steps': typing.List[typing.Any]}),
 ('__class__', sklearn.pipeline.Pipeline),
 ('__delattr__',
  <method-wrapper '__delattr__' of Pipeline object at 0x7f396d216940>),
 ('__dict__',
  {'steps': [('pipeline',
     Pipeline(steps=[('polynomialfeatures', PolynomialFeatures())]))],
   'memory': None,
   'verbose': False}),
 ('__dir__', <function Pipeline.__dir__()>),
 ('__doc__',
  "\n    Pipeline of transforms with a final estimator.\n\n    Sequentially apply a list of transforms and a final estimator.\n    Intermediate steps of the pipeline must be 'transforms', that is, they\n    must implement fit and transform methods.\n    The final estimator only needs to implement fit.\n    The transformers in the pipeline can be cached using ``memory`` argument.\n\n    The purpose of the pipeline is to assemble several steps that can be\n    cross-validated together while setting different parameters.\n    For this, it enables setting pa