In [8]:
import numpy as np
from sklearn.model_selection import validation_curve
from sklearn.linear_model import LinearRegression, SGDRegressor, Ridge
import pandas as pd

In [2]:
df = pd.read_csv('./data_multi.csv')
df

x_1       x_2           y
0   1.054452 -1.070753  -81.464433
1  -0.362741 -0.634322  -78.752795
2  -0.854096  0.313068    2.218414
3   1.326386  0.298238   52.234160
4  -0.461585 -1.315907 -159.639258
..       ...       ...         ...
95  0.823504  0.771791   86.316340
96  0.976639  0.208275   83.136943
97 -1.347759  1.883151  157.404615
98  0.052165 -1.104383 -136.511136
99 -1.726283 -0.813146 -143.452015

[100 rows x 3 columns]

In [3]:
np.random.seed(0)
X = df[['x_1', 'x_2']].to_numpy()
y = df['y'].to_numpy()
indices = np.arange(y.shape[0])
np.random.shuffle(indices)
X, y = X[indices], y[indices]

In [4]:
train_scores, valid_scores = validation_curve(Ridge(), X, y, "alpha",
                                              np.logspace(-7, 3, 3),
                                              cv=5)
train_scores

/home/jo/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:68: FutureWarning: Pass param_name=alpha, param_range=[1.e-07 1.e-02 1.e+03] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


array([[0.92924098, 0.9289334 , 0.93492816, 0.9237022 , 0.94248464],
       [0.92924097, 0.92893339, 0.93492815, 0.92370218, 0.94248463],
       [0.14225323, 0.13122965, 0.14837704, 0.11964926, 0.14268903]])

In [5]:
valid_scores

array([[ 0.93665308,  0.93747486,  0.89909186,  0.94330455,  0.87060857],
       [ 0.93665362,  0.93745479,  0.89911908,  0.94331256,  0.87060808],
       [-0.00787713,  0.11368082,  0.08481195, -0.03048749, -0.01153978]])

In [7]:
reg = LinearRegression()
reg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

In [13]:
reg = SGDRegressor(learning_rate='constant')

In [14]:
reg.get_params()

{'alpha': 0.0001,
 'average': False,
 'early_stopping': False,
 'epsilon': 0.1,
 'eta0': 0.01,
 'fit_intercept': True,
 'l1_ratio': 0.15,
 'learning_rate': 'constant',
 'loss': 'squared_loss',
 'max_iter': 1000,
 'n_iter_no_change': 5,
 'penalty': 'l2',
 'power_t': 0.25,
 'random_state': None,
 'shuffle': True,
 'tol': 0.001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [18]:
train_scores, valid_scores = validation_curve(SGDRegressor(learning_rate='constant'), X, y, "alpha",
                                              np.linspace(0, 3, 3),
                                              cv=5)

/home/jo/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:68: FutureWarning: Pass param_name=alpha, param_range=[0.  1.5 3. ] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [19]:
train_scores

array([[0.9292355 , 0.92880091, 0.93491356, 0.92368299, 0.94239132],
       [0.63980705, 0.61252418, 0.62654043, 0.55052649, 0.62460485],
       [0.47197706, 0.4359411 , 0.38820661, 0.33944149, 0.41988964]])